version = "1.0"

[main]
name = "My Webapp configuration"

    [main.sftp]
    name.en = "SFTP access"
    name.fr = "Accès SFTP"

        [main.sftp.with_sftp]
        ask.en = "Do you need a SFTP access?"
        ask.fr = "Avez-vous besoin d'un accès SFTP ?"
        type = "boolean"
        default = true

        [main.sftp.password]
        ask.en = "Set a password for the SFTP access"
        ask.fr = "Définir un mot de passe pour l’accès SFTP"
        type = "password"
        optional = true
        visible = "with_sftp"
        help.en = "If a password already exist, leave blank and it will not be replaced."
        help.fr = "Si un mot de passe existe déjà, laissez vide et il ne sera pas remplacé."

    [main.code_error]
    name = "Html Custom error"

        [main.code_error.custom_error_file]
        ask = "Activate the custom error file use"
        type = "boolean"
        default = false
        help = "Once custom error enabled, you can add/create a custom `404.html` file in a directory `www\\error`."

    [main.php_fpm_config]
    name = "PHP-FPM configuration"

        [main.php_fpm_config.phpversion]
        ask = "PHP version"
        type = "select"
        choices = ["none", "7.4", "8.0", "8.1", "8.2", "8.3"]
        default = "none"

        [main.php_fpm_config.fpm_footprint]
        visible = "phpversion != 'none'"
        ask = "Memory footprint of the service?"
        type = "select"
        choices.low = "Low, <= 20Mb per pool"
        choices.medium = "Medium, between 20Mb and 40Mb per pool"
        choices.high = "High, > 40Mb per pool"
        choices.specific = "Use specific value"
        default = "low"

        [main.php_fpm_config.fpm_free_footprint]
        visible = "fpm_footprint == 'specific' && phpversion != 'none'"
        ask = "Memory footprint of the service?"
        type = "number"
        default = "0"
        help = "Free field to specify exactly the footprint in Mb if you don't want to use one of the three previous values."

        [main.php_fpm_config.fpm_usage]
        visible = "phpversion != 'none'"
        ask = "Expected usage of the service?"
        type = "select"
        choices = ["low", "medium", "high"]
        default = "low"
        help = "low: Personal usage, behind the sso. No RAM footprint when not used, but the impact on the processor can be high if many users are using the service.<br>medium: Low usage, few people or/and publicly accessible. Low RAM footprint, medium processor footprint when used.<br>high: High usage, frequently visited website. High RAM footprint, but lower on processor usage and quickly responding."

# TODO: Add protected_path as tags, which are created as permission "label (path)", so admin can protect a specific path
#    [main.permissions]
#        [main.permissions.proteced_path]
#        ask = "Protected path"
#        help = "A permission will be created so you can restrict the access to a subpath of the web app."
#        type = "tags"
    
