test_format = 1.0

[default]

    # -------------------------------
    # Default args to use for install
    # -------------------------------

    args.with_sftp = "1"
    args.custom_error_file = "0"
    args.password = "SuperDuper_StrongPassw0rd"
    args.database = "none"
    args.phpversion = "8.3"
    test_upgrade_from.bf5d3ed.name = "1.0~ynh14"
    test_upgrade_from.bf5d3ed.args.with_mysql = "0"
    test_upgrade_from.bf5d3ed.args.domain = "sub.domain.tld"
    test_upgrade_from.bf5d3ed.args.path = "/"
    test_upgrade_from.bf5d3ed.args.password = "SuperDuper_StrongPassw0rd"

[83_test]

    only = ["install.subdir", "backup_restore", "upgrade" ]
    args.phpversion = "8.3"

[84_test]

    only = ["install.subdir", "backup_restore", "upgrade" ]
    args.phpversion = "8.4"

[none_test]

    args.phpversion = "none"

[mysql_test]

    only = ["install.subdir", "backup_restore", "upgrade", "upgrade.bf5d3ed" ]
    args.database = "mysql"
    test_upgrade_from.bf5d3ed.name = "1.0~ynh14"
    test_upgrade_from.bf5d3ed.args.with_mysql = "1"
    test_upgrade_from.bf5d3ed.args.domain = "sub.domain.tld"
    test_upgrade_from.bf5d3ed.args.path = "/"
    test_upgrade_from.bf5d3ed.args.password = "SuperDuper_StrongPassw0rd"

[postgresql_test]

    only = ["install.subdir", "backup_restore", "upgrade" ]
    args.database = "postgresql"

[custom_error_file_test]

    args.custom_error_file = "1"
    test_upgrade_from.bf5d3ed.name = "1.0~ynh14"
    test_upgrade_from.bf5d3ed.args.with_mysql = "0"
    test_upgrade_from.bf5d3ed.args.domain = "sub.domain.tld"
    test_upgrade_from.bf5d3ed.args.path = "/"
    test_upgrade_from.bf5d3ed.args.password = "SuperDuper_StrongPassw0rd"

# Tests pour les diff√©rents modes d'installation
[standard_test]
    args.install_mode = "standard"
    only = ["install.subdir", "backup_restore", "upgrade" ]

[frontcontroller_www_test]
    args.install_mode = "front_controller_www"
    only = ["install.subdir", "backup_restore", "upgrade" ]

[frontcontroller_public_test]
    args.install_mode = "front_controller_public"
    only = ["install.subdir", "backup_restore", "upgrade" ]
